name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.name ${{ secrets.GITUSERNAME }}
      - run: git config --global user.email ${{ secrets.GITEMAIL }}
      - run: git config --global user.password ${{ secrets.ACCESSSECRET }}
      - run: |
          ls
          git clone https://${{ secrets.TOKEN }}@github.com/yeasin72/actiontest.git
          cd actiontest
          rm -rf .git
          cd ..
          git clone https://${{ secrets.ACCESSSECRET }}@github.com/Saidiislam/Nanbu-motel.git
          cd Nanbu-motel
          git checkout -b yeasin@v7.0.${{ github.run_number }}
          mkdir mobile
          cd ..
          mv /actiontest /Nanbu-motel/mobile
          git add .
          git commit "test from auto"
          git push --set-upstream origin yeasin@v7.0.${{ github.run_number }}
      - run: ls
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Nanbu-motel"
          tag: v7.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      
