name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      #- run: git config --global user.name ${{ secrets.GITUSERNAME }}
      #- run: git config --global user.name ${{ secrets.GITEMAIL }}
      - run: git clone https://${{ secrets.ACCESSSECRET }}@github.com/Saidiislam/Nanbu-motel.git
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Nanbu-motel/public"
          tag: v7.0.${{ github.run_number }}
      
