name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      #- run: git config --global user.name ${{ secrets.GITUSERNAME }}
      #- run: git config --global user.name ${{ secrets.GITEMAIL }}
      - run: |
          ls
          git clone https://${{ secrets.ACCESSSECRET }}@github.com/Saidiislam/Nanbu-motel.git
          cd Nanbu-motel
          rm -rf .git
      - run: ls
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          -run: cd Nanbu-motel
          artifacts: "Nanbu-motel"
          tag: v7.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      
