name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://${{ secrets.TOKEN }}@github.com/yeasin72/actiontest.git
          cd actiontest
          rm -rf .git
          cd ..
          git clone https://${{ secrets.TOKEN }}@github.com/Saidiislam/Nanbu-motel.git
          cd Nanbu-motel
          git config user.name "yeasin72"
          git config user.email "efun800@gmail.com"
          git checkout -b yeasin@v7.0.${{ github.run_number }}
          mkdir mobile
          cd ..
          mv actiontest/ Nanbu-motel/mobile/
          cd Nanbu-motel
          git add .
          git commit "test from auto"
          git push --set-upstream origin yeasin@v7.0.${{ github.run_number }}
          git push --set-upstream https://yeasin72:${{ secrets.TOKEN }}@github.com/Saidiislam/Nanbu-motel.git yeasin@v7.0.${{ github.run_number }}
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Nanbu-motel"
          tag: v7.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      
